# Generated by Django 4.1 on 2024-10-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
